name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Grunt
      run: grunt

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build-artifact          # Name of the artifact
        path: dist/                  # Path to the files/folder to upload
        if-no-files-found: warn      # warn, error, or ignore
        retention-days: 7            # optional, default 90
        compression-level: 6         # optional, default 6
        overwrite: true              # optional, default false
        include-hidden-files: false  # optional, default false
